{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "a10tkc.serviceAccountName" . }}-serviceaccount
  labels:
    {{- include "a10tkc.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "a10tkc.serviceAccountName" . }}-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "a10tkc.serviceAccountName" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "a10tkc.serviceAccountName" . }}-serviceaccount
    namespace: {{ .Release.Namespace }}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "a10tkc.serviceAccountName" . }}-clusterrole
rules:
  - apiGroups: "*"
    resources: "*"
    verbs: "*"

