{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "a10tkc.serviceAccountName" . }}-serviceaccount
  labels:
    {{- include "a10tkc.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "a10tkc.serviceAccountName" . }}-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "a10tkc.serviceAccountName" . }}-serviceaccount
    namespace: {{ .Release.Namespace }}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "a10tkc.serviceAccountName" . }}-clusterrole
rules:
  - apiGroups: ["*", "extensions","nodes","networking.k8s.io"]
    resources: ["secrets", "configmaps","endpoints","events","ingresses","ingresses/status","services","nodes", "routes"]
    verbs: ["get", "watch", "list","patch","create","update"]
  - apiGroups: ["a10tkc.a10networks.com"]
    resources: ["natpools", "healthmonitors", "virtualservers", "servicegroups","serverssls", "virtualports","templateciphers","clientssls","serverssls/status","clientssls/status"]
    verbs: ["get", "watch", "list","patch","create","update"]
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["ippools", "ipreservations", "blockaffinities", "ipamconfigs", "ipamblocks","ipamhandles"]
    verbs: ["*"]
  - apiGroups:
      - "config.openshift.io"
    resources:
      - 'clusteroperators'
    verbs:
      - 'get'
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - 'clusterrolebindings'
      - 'clusterroles'
    verbs:
      - 'get'
      - 'create'
      - 'delete'
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - 'mutatingwebhookconfigurations'
    verbs:
      - 'get'
      - 'create'
      - 'list'
      - 'watch'
      - 'patch'
      - 'delete'
  - apiGroups:
      - "authentication.k8s.io"
    resources:
      - 'tokenreviews'
    verbs:
      - 'create'
  - apiGroups:
      - "authorization.k8s.io"
    resources:
      - 'subjectaccessreviews'
    verbs:
      - 'create'

